export const pathnames = {
  public: {
    layout: "/",
    homepage: "",
    news: "/tin-tuc",
    rentProperty: "/nha-dat-cho-thue",
    soldProperty: "/nha-dat-ban",
    resetPassword: "/reset-password/:token",
    Property_Detail: "/detail",
    Property_Detail__ID: "/detail/:pid",
    Property_Edit: "/edit",
    Property_Edit__ID: "/edit/:pid",
  },
  users: {
    layout: "/thanh-vien/",
    personal: "ca-nhan",
    general: "tong-quan",
    createPost: "tao-moi-tin-dang",
    managePost: "quan-ly-tin-dang",
    manageDraft: "quan-ly-tin-nhap",
    updatePhone: "cap-nhat-sdt",
    updateEmail: "cap-nhat-email",
    manageBalance: "quan-ly-tin-chinh",
    deposit: "nap-tien",
    paymentHistory: "lich-su-thanh-toan",
  },
};
