version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5100:5100"
    env_file:
      - ./server/.env   # Change BE to server
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
