module.exports = {
    enumData: {
        Pricings: ["Thường", "Đồng", "Bạc", "Vàng", "Kim Cương"],
        postStatus: ["Còn trống", "Đang cập nhật", "Đã bàn giao"],
        propertyTypes: [
            "Căn hộ chung cư",
            "Nhà mặt phố",
            "Nhà riêng",
            "Nhà phố thương mại",
            "Biệt thự",
            "Đất nền",
            "Bán đất",
            "Trang trại",
            "Khu nghĩ dưỡng",
            "Kho",
            "Nhà xưởng",
            "Khác"
        ],
        listingTypes: ["Bán", "Cho thuê"],
        directions: ["Đông - Bắc", "Tây - Nam", "Đông - Nam", "Tây - Bắc", "Đông", "Tây", "Nam", "Bắc"],

    },
    pricings: [
        {
            name: "Thường",
            isDisplayImmedialy: false,
            levelShowDescription: 0.1,
            priority: 1,
            requireScore: 0,
            requireScoreNextLevel: 200000,
            expiredDay: 1,
            price: 0,
            imgUrl: "/svg/base.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: "Đồng",
            isDisplayImmedialy: false,
            levelShowDescription: 0.2,
            priority: 2,
            requireScore: 200000,
            requireScoreNextLevel: 500000,
            expiredDay: 3,
            price: 200000,
            imgUrl: "/svg/bronze.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: "Bạc",
            isDisplayImmedialy: false,
            levelShowDescription: 0.3,
            priority: 3,
            requireScore: 500000,
            requireScoreNextLevel: 1000000,
            expiredDay: 10,
            price: 500000,
            imgUrl: "/svg/silver.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: "Vàng",
            isDisplayImmedialy: false,
            levelShowDescription: 0.4,
            priority: 4,
            requireScore: 1000000,
            requireScoreNextLevel: 2000000,
            expiredDay: 15,
            price: 1000000,
            imgUrl: "/svg/gold.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: "Kim Cương",
            isDisplayImmedialy: false,
            levelShowDescription: 0.5,
            priority: 5,
            requireScore: 2000000,
            requireScoreNextLevel: -1,
            expiredDay: 30,
            price: 1500000,
            imgUrl: "/svg/diamond.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        }
    ]
};